### ISSUE TITLE
FIPS codes for map?

### ISSUE THREAD

**Issue by kwstat** [axismaps/colorbrewer#10]
Is there any way to get FIPS codes added to colorbrewer/map/map.svg so that I can work with the map in a custom environment?

**Comment by awoodruff** [comment]
Unfortunately, not easily at this point. That map is just plain vector graphics that have managed to survive all the way from the original Flash version of ColorBrewer until now, so it probably lost all its geographic attributes long ago. The best I can suggest is to see if there's a way to georeference an SVG and then do some kind of spatial join to transfer the color classes to an actual counties geodata file, but in any case we don't have FIPS codes (or any other data) for the map on this end.

**Comment by kwstat** [comment]
Thanks for the information.
