### ISSUE TITLE
License

### ISSUE THREAD

**Issue by awoodruff** [axismaps/colorbrewer#7]
This code/repo should have some kind of license file, and we should be sure Cindy is okay with whatever it is.

**Comment by davidheyman** [comment]
I don't see any reason not to use MIT

**Comment by tcrossland** [comment]
There's a license on ColorBrewer's [updates](http://www.personal.psu.edu/cab38/ColorBrewer/ColorBrewer_updates.html) page, apparently based on ASL 2.0.

**Comment by awoodruff** [comment]
License added via #17
