### ISSUE TITLE
add new schemes

### ISSUE THREAD

**Issue by pierrebrt** [axismaps/colorbrewer#9]
Hello,

Do you think you may add a few new schemes, just like in D3.js 4.0 : https://github.com/d3/d3-scale/blob/master/README.md#interpolateViridis

**Comment by awoodruff** [comment]
D3 and other sources have got some good color schemes, but ColorBrewer is specifically for the schemes Cindy Brewer developed in her research—so the only foreseeable additions would be if she decides to expand on that research some day!
